### ISSUE TITLE
multi-monitor support seems to not work

### ISSUE THREAD

**Issue by keysmashes** [anko/hudkit#11]
running the example page, sometimes it'll open itself like this:

![Screenshot from 2021-04-27 14-38-12](https://user-images.githubusercontent.com/9433472/116251112-415c4180-a766-11eb-96a4-0e7a8bc7cbc3.png)

sometimes like this:

![Screenshot from 2021-04-27 14-40-13](https://user-images.githubusercontent.com/9433472/116251357-7ec0cf00-a766-11eb-80f9-5db756b616da.png)

and other times the window just won't be visible at all.

i'm using i3wm on ubuntu 18.04; i have two 1080p monitors side-by-side:

```
$ xrandr
Screen 0: minimum 8 x 8, current 3840 x 1080, maximum 32767 x 32767
DP-0 disconnected (normal left inverted right x axis y axis)
DP-1 disconnected (normal left inverted right x axis y axis)
eDP-1-1 connected primary 1920x1080+0+0 (normal left inverted right x axis y axis) 344mm x 194mm
   1920x1080     60.00*+  59.97    59.96    59.93    48.00  
   1680x1050     59.95    59.88  
   1600x1024     60.17  
   1400x1050     59.98  
   1600x900      59.99    59.94    59.95    59.82  
   1280x1024     60.02  
   1440x900      59.89  
   1400x900      59.96    59.88  
   1280x960      60.00  
   1440x810      60.00    59.97  
   1368x768      59.88    59.85  
   1360x768      59.80    59.96  
   1280x800      59.99    59.97    59.81    59.91  
   1152x864      60.00  
   1280x720      60.00    59.99    59.86    59.74  
   1024x768      60.04    60.00  
   960x720       60.00  
   928x696       60.05  
   896x672       60.01  
   1024x576      59.95    59.96    59.90    59.82  
   960x600       59.93    60.00  
   960x540       59.96    59.99    59.63    59.82  
   800x600       60.00    60.32    56.25  
   840x525       60.01    59.88  
   864x486       59.92    59.57  
   800x512       60.17  
   700x525       59.98  
   800x450       59.95    59.82  
   640x512       60.02  
   720x450       59.89  
   700x450       59.96    59.88  
   640x480       60.00    59.94  
   720x405       59.51    58.99  
   684x384       59.88    59.85  
   680x384       59.80    59.96  
   640x400       59.88    59.98  
   576x432       60.06  
   640x360       59.86    59.83    59.84    59.32  
   512x384       60.00  
   512x288       60.00    59.92  
   480x270       59.63    59.82  
   400x300       60.32    56.34  
   432x243       59.92    59.57  
   320x240       60.05  
   360x202       59.51    59.13  
   320x180       59.84    59.32  
DP-1-1 disconnected (normal left inverted right x axis y axis)
HDMI-1-1 disconnected (normal left inverted right x axis y axis)
HDMI-1-2 connected 1920x1080+1920+0 (normal left inverted right x axis y axis) 477mm x 268mm
   1920x1080     60.00*+  59.94  
   1680x1050     59.88  
   1280x1024     75.02    60.02  
   1440x900      59.90  
   1280x960      60.00  
   1280x720      60.00    59.94  
   1024x768      75.03    70.07    60.00  
   832x624       74.55  
   800x600       72.19    75.00    60.32    56.25  
   720x480       60.00    59.94  
   640x480       75.00    72.81    66.67    60.00    59.94  
   720x400       70.08  
```

presumably this is something weird about my setup, given it sounds like it works for other people...

**Comment by anko** [comment]
Hi and thanks for reporting! :sparkles:

I use i3wm with 2 monitors too, but without this issue, so I don't have an immediate solution, but I do have some ideas.  Brain dump follows.

There are 2 separate surprises in this screenshot:

1. Based on where the window edges' drop shadows appear, the overlay window itself is positioned wrong.  (Not the in-web-page content, but the actual window.)

   :thought_balloon:: That might suggest some other program is moving the overlay window.  It looks to me as though in the first screenshot, the window is positioned centered relative to the right monitor, and in the second screenshot, centered relative to the left monitor.  Perhaps there is a program on your system that automatically positions new windows centered within the currently active monitor?

2. The overlay window's entire area should have a partially opaque blue background, but it looks to be completely transparent.

   :thought_balloon:: This likely means the JavaScript on the example `page.html` errored out before drawing the blue monitor rectangles on screen.  Perhaps I've goofed and used some cutting-edge JS feature in the example that Ubuntu's libwebkit doesn't support yet?

- - -

If you're feeling up for a debugging journey, any of the following diagnostics would help a lot:

The second issue (probably JS erroring out?) is likely easier:

 1. Edit the example's `run.sh` to pass the `--inspect` flag to hudkit;

   ```diff
   -../hudkit "file://$PWD/page.html"
   +../hudkit --inspect "file://$PWD/page.html"
   ```

 2. What console entries (if any) does the *Web Inspector* window's *Console* tab contain?  Clicking one and <kbd>Ctrl</kbd><kbd>a</kbd> selects all if you want to copy-paste.


The first issue (wrong window position) is trickier to narrow down, because the space of things that could cause it is pretty big.  But these would help:
 
- Try editing `main.c` to directly give integers of your choice to [`gtk_window_move` and `gtk_window_resize`](https://github.com/anko/hudkit/blob/2918ccb042d9ee204a0ba57e58c6feda28765163/main.c#L874-L877) (instead of using the `x`, `y`, `width` and `height` variables) and seeing what happens.  If setting the window to a different position in the code makes no difference, that would definitely imply some other program is moving the overlay window after it's created.

- Try disconnecting or connecting a monitor using `xrandr`, while the hudkit example is running.  That should trigger hudkit to resize the overlay window to the new desktop area.  If it positions correctly then, that would rule out bugs in hudkit's own window positioning.

- If it seems based on the above that something is resizing the window after creation, you could back up your i3 config, copy the default from `/etc/i3/config`, and if it works then, gradually bring in parts of your actual config until it breaks.  Even if it's just something weird in your setup, it would make a good FAQ entry for the next person.

**Comment by keysmashes** [comment]
passing `--inspect` shows nothing at all in the console, bizarrely:

![image](https://user-images.githubusercontent.com/9433472/116787217-e777b680-aa9a-11eb-93a5-b26d2dbdd8d5.png)

and the `monitor-frame-container` is totally empty.

~the window seems to be consistently opening in the correct position now, though – i just upgraded my gpu drivers, but don't _think_ i changed anything else.~ it works fine if i pass `--inspect`, but apparently just doesn't show up at all now if i don't. who knows...

adding some logging to the embedded js, it seems like `Hudkit.getMonitorLayout` is hanging? adding some more logging, it seems like the generated js (specifically, the name of my external monitor) is kinda Weird:

```
got monitor model: 'eDP-1-1' (length 7)
got monitor model: 'HDMI-1-2' (length 8)
final buffer: [{name:'eDP-1-1',x:0,y:0,width:1920,height:1080},{name:'HDMI-1-2d~',x:1920,y:0,width:1920,height:1080},]
```

there are consistently a few junk characters after `HDMI-1-2`; they change each run.

if i memset `escaped_monitor_model_string` full of zeroes in `on_js_call_get_monitor_layout` just after it's declared, the problem goes away. aiui, only statics and globals are initialised to zero automatically, so i guess it needs zeroing out explicitly?

**Comment by anko** [comment]
> if i memset `escaped_monitor_model_string` full of zeroes in `on_js_call_get_monitor_layout` just after it's declared, the problem goes away. aiui, only statics and globals are initialised to zero automatically, so i guess it needs zeroing out explicitly?

Oops! :frowning:  You're right.  I thought I checked this; I even wrote [a comment](https://github.com/anko/hudkit/blob/822e13cee0eef22677962f7d07e6493a355b4de8/main.c#L196-L197), which on further reading is altogether wrong.  Why was I even trying to optimise out a 1-char `memset`?

Memsetting a `'\0'` at the end should be enough; the rest of the buffer being uninitialised junk doesn't matter.

**Comment by anko** [comment]
Fix is on `master`.  Check it works for you?

It's a great mystery why this has never happened on my machine.  [Nasal demons](http://catb.org/jargon/html/N/nasal-demons.html) are scary.

**Comment by keysmashes** [comment]
yep, works for me! thanks :)
