### ISSUE TITLE
multi-display bug and feature request

### ISSUE THREAD

**Issue by grkblood13** [anko/hudkit#2]
If I launch the command from the 2nd of two monitors it'll take the overall width of the combined displays and initiate the HUD on the second monitor. This results in the first monitor not having the HUD and the second one displaying a HUD that appears stretched.

feature request) add the ability to only display HUD on default monitor when multiple are present via a command line flag

bug report) HUD incorrectly estimates size and position when not initialized from the first of a multiple display setup.

**Comment by anko** [comment]
> If I launch the command from the 2nd of two monitors it'll take the overall width of the combined displays and initiate the HUD on the second monitor.

I don't have a second monitor for a few more weeks because life :rainbow:, so my ability to help is a little limited.

Either way, these details would help:

 - Clarifying: This only happens when you start hudkit from the second monitor?
 - Do you have a screenshot?
 - What desktop environment or WM are you using?
 - When you run the example in a terminal, what output do you get? Do the monitor positions and sizes it reports look right there?

> feature request) add the ability to only display HUD on default monitor when multiple are present via a command line flag

Good idea!

> bug report) HUD incorrectly estimates size and position when not initialized from the first of a multiple display setup.

This refers to the same problem as the first paragraph, right?

**Comment by anko** [comment]
Finally got around to looking at this with my brain turned on.

Excuses excuses:  On a previous machine I couldn't repro this at all, and Hudkit would always get its window positioned at absolute 0,0.  On my current machine, it would position at the top-left of the window it was started from which is wrong (as you observed). :shrug:

**Comment by anko** [comment]
Oh right, there was also a feature request.

> add the ability to only display HUD on default monitor when multiple are present via a command line flag

Nah.  Too complicated.  You can instead hide or show stuff in your web page's context, by [reading the `Hudkit.monitors` variable from JavaScript](https://github.com/anko/hudkit#javascript-api) and positioning your HUDs there, then hiding or showing what's on the appropriate monitors.
